import 'listing.dart';

const List<Listing> kExampleListings = <Listing>[
  Listing(
    id: 'example_tashkent_yunusabad_1',
    hostId: 'example_host_1',
    hostName: 'Malika Karimova',
    hostPhone: '+998901110011',
    title: 'Skyline apartment near Minor Mosque',
    city: 'Tashkent',
    district: 'Yunusabad',
    type: ListingType.apartment,
    maxGuests: 4,
    minDays: 1,
    maxDays: 30,
    nightlyPriceUzs: 540000,
    isActive: true,
    amenities: <ListingAmenity>[
      ListingAmenity.wifi,
      ListingAmenity.airConditioner,
      ListingAmenity.kitchen,
      ListingAmenity.washingMachine,
      ListingAmenity.instantConfirm,
    ],
    imageUrls: <String>[
      'assets/images/home1.png',
      'assets/images/home2.png',
      'assets/images/home3.png',
    ],
    description:
        'Panoramic city-view apartment with modern interior, fast Wi-Fi, and quick metro access.',
    landmark: '41.352312, 69.287169',
    metro: 'Shahriston',
  ),
  Listing(
    id: 'example_tashkent_mirobod_2',
    hostId: 'example_host_2',
    hostName: 'Dilshod Rakhimov',
    hostPhone: '+998901110022',
    title: 'Designer loft near Tashkent City',
    city: 'Tashkent',
    district: 'Mirobod',
    type: ListingType.apartment,
    maxGuests: 2,
    minDays: 1,
    maxDays: 20,
    nightlyPriceUzs: 510000,
    isActive: true,
    amenities: <ListingAmenity>[
      ListingAmenity.wifi,
      ListingAmenity.airConditioner,
      ListingAmenity.kitchen,
      ListingAmenity.privateBathroom,
    ],
    imageUrls: <String>[
      'assets/images/home2.png',
      'assets/images/home3.png',
      'assets/images/home4.png',
    ],
    description:
        'Premium loft with cozy lighting, strong AC, and a comfortable workspace.',
    landmark: '41.311861, 69.245982',
    metro: 'Kosmonavtlar',
  ),
  Listing(
    id: 'example_tashkent_chilonzor_3',
    hostId: 'example_host_3',
    hostName: 'Madina Yuldasheva',
    hostPhone: '+998901110033',
    title: 'Family apartment near Magic City',
    city: 'Tashkent',
    district: 'Chilonzor',
    type: ListingType.apartment,
    maxGuests: 5,
    minDays: 2,
    maxDays: 21,
    nightlyPriceUzs: 610000,
    isActive: true,
    amenities: <ListingAmenity>[
      ListingAmenity.wifi,
      ListingAmenity.kitchen,
      ListingAmenity.washingMachine,
      ListingAmenity.kidsAllowed,
      ListingAmenity.privateBathroom,
    ],
    imageUrls: <String>[
      'assets/images/home4.png',
      'assets/images/home1.png',
      'assets/images/home2.png',
    ],
    description:
        'Spacious family-friendly stay close to city attractions and parks.',
    landmark: '41.299486, 69.240908',
    metro: 'Novza',
  ),
  Listing(
    id: 'example_tashkent_yakkasaroy_4',
    hostId: 'example_host_4',
    hostName: 'Kamola Ismoilova',
    hostPhone: '+998901110044',
    title: 'Quiet room with balcony',
    city: 'Tashkent',
    district: 'Yakkasaroy',
    type: ListingType.room,
    maxGuests: 2,
    minDays: 1,
    maxDays: 10,
    nightlyPriceUzs: 290000,
    isActive: true,
    amenities: <ListingAmenity>[
      ListingAmenity.wifi,
      ListingAmenity.hostLivesTogether,
      ListingAmenity.privateBathroom,
    ],
    imageUrls: <String>['assets/images/home3.png', 'assets/images/home2.png'],
    description:
        'Private room in a stylish apartment, great for solo trips and quick business stays.',
    landmark: '41.292514, 69.267821',
    metro: 'Oybek',
  ),
  Listing(
    id: 'example_samarkand_registan_5',
    hostId: 'example_host_5',
    hostName: 'Jasur Nematov',
    hostPhone: '+998901110055',
    title: 'Elegant apartment near Registan',
    city: 'Samarkand',
    district: 'Registan',
    type: ListingType.apartment,
    maxGuests: 4,
    minDays: 1,
    maxDays: 14,
    nightlyPriceUzs: 470000,
    isActive: true,
    amenities: <ListingAmenity>[
      ListingAmenity.wifi,
      ListingAmenity.airConditioner,
      ListingAmenity.kitchen,
      ListingAmenity.washingMachine,
    ],
    imageUrls: <String>[
      'assets/images/home4.png',
      'assets/images/home1.png',
      'assets/images/home2.png',
    ],
    description:
        'A bright and calm apartment close to Registan, perfect for short cultural stays.',
    landmark: '39.654182, 66.975783',
    metro: null,
  ),
  Listing(
    id: 'example_samarkand_siyob_6',
    hostId: 'example_host_6',
    hostName: 'Saida Tursunova',
    hostPhone: '+998901110066',
    title: 'Warm loft near Siyob bazaar',
    city: 'Samarkand',
    district: 'Siyob',
    type: ListingType.homePart,
    maxGuests: 3,
    minDays: 1,
    maxDays: 20,
    nightlyPriceUzs: 360000,
    isActive: true,
    amenities: <ListingAmenity>[
      ListingAmenity.wifi,
      ListingAmenity.kitchen,
      ListingAmenity.privateBathroom,
      ListingAmenity.instantConfirm,
    ],
    imageUrls: <String>['assets/images/home3.png', 'assets/images/home2.png'],
    description:
        'Compact loft with authentic local vibe and easy access to old city routes.',
    landmark: '39.673954, 66.988142',
    metro: null,
  ),
  Listing(
    id: 'example_bukhara_oldcity_7',
    hostId: 'example_host_7',
    hostName: 'Rustam Safarov',
    hostPhone: '+998901110077',
    title: 'Boutique apartment in Old Bukhara',
    city: 'Bukhara',
    district: 'Old City',
    type: ListingType.apartment,
    maxGuests: 4,
    minDays: 1,
    maxDays: 15,
    nightlyPriceUzs: 520000,
    isActive: true,
    amenities: <ListingAmenity>[
      ListingAmenity.wifi,
      ListingAmenity.airConditioner,
      ListingAmenity.kitchen,
      ListingAmenity.privateBathroom,
    ],
    imageUrls: <String>[
      'assets/images/home1.png',
      'assets/images/home4.png',
      'assets/images/home3.png',
    ],
    description:
        'Stylish short-stay apartment near historical sights and evening walking streets.',
    landmark: '39.775338, 64.415194',
    metro: null,
  ),
  Listing(
    id: 'example_bukhara_lyabi_8',
    hostId: 'example_host_8',
    hostName: 'Nargiza Muminova',
    hostPhone: '+998901110088',
    title: 'Family stay near Lyabi-Hauz',
    city: 'Bukhara',
    district: 'Lyabi-Hauz',
    type: ListingType.apartment,
    maxGuests: 5,
    minDays: 2,
    maxDays: 21,
    nightlyPriceUzs: 580000,
    isActive: true,
    amenities: <ListingAmenity>[
      ListingAmenity.wifi,
      ListingAmenity.kitchen,
      ListingAmenity.washingMachine,
      ListingAmenity.kidsAllowed,
      ListingAmenity.privateBathroom,
    ],
    imageUrls: <String>[
      'assets/images/home2.png',
      'assets/images/home1.png',
      'assets/images/home4.png',
    ],
    description:
        'Spacious apartment for families with a clean modern kitchen and peaceful inner yard.',
    landmark: '39.774982, 64.421603',
    metro: null,
  ),
  Listing(
    id: 'example_khiva_itchan_9',
    hostId: 'example_host_9',
    hostName: 'Bekzod Matyakubov',
    hostPhone: '+998901110099',
    title: 'Cozy room by Ichan Kala walls',
    city: 'Khiva',
    district: 'Ichan Kala',
    type: ListingType.room,
    maxGuests: 2,
    minDays: 1,
    maxDays: 12,
    nightlyPriceUzs: 310000,
    isActive: true,
    amenities: <ListingAmenity>[
      ListingAmenity.wifi,
      ListingAmenity.hostLivesTogether,
      ListingAmenity.airConditioner,
      ListingAmenity.privateBathroom,
    ],
    imageUrls: <String>['assets/images/home3.png', 'assets/images/home2.png'],
    description:
        'Comfortable private room for travelers who want to stay next to Khiva heritage sites.',
    landmark: '41.378621, 60.361944',
    metro: null,
  ),
  Listing(
    id: 'example_fergana_center_10',
    hostId: 'example_host_10',
    hostName: 'Zarina Ruzmatova',
    hostPhone: '+998901110100',
    title: 'Modern apartment in Fergana center',
    city: 'Fergana',
    district: 'City Center',
    type: ListingType.apartment,
    maxGuests: 3,
    minDays: 1,
    maxDays: 18,
    nightlyPriceUzs: 390000,
    isActive: true,
    amenities: <ListingAmenity>[
      ListingAmenity.wifi,
      ListingAmenity.airConditioner,
      ListingAmenity.kitchen,
      ListingAmenity.parking,
    ],
    imageUrls: <String>['assets/images/home4.png', 'assets/images/home1.png'],
    description:
        'Clean and modern apartment close to city cafes and main transport routes.',
    landmark: '40.389775, 71.784592',
    metro: null,
  ),
  Listing(
    id: 'example_namangan_chorsu_11',
    hostId: 'example_host_11',
    hostName: 'Sardor Ergashev',
    hostPhone: '+998901110111',
    title: 'Garden-view apartment in Namangan',
    city: 'Namangan',
    district: 'Chorsu',
    type: ListingType.homePart,
    maxGuests: 4,
    minDays: 1,
    maxDays: 30,
    nightlyPriceUzs: 330000,
    isActive: true,
    amenities: <ListingAmenity>[
      ListingAmenity.wifi,
      ListingAmenity.kitchen,
      ListingAmenity.washingMachine,
      ListingAmenity.kidsAllowed,
    ],
    imageUrls: <String>[
      'assets/images/home1.png',
      'assets/images/home2.png',
      'assets/images/home3.png',
    ],
    description:
        'A calm home-part stay with green view and practical amenities for families.',
    landmark: '41.002184, 71.672981',
    metro: null,
  ),
  Listing(
    id: 'example_andijan_center_12',
    hostId: 'example_host_12',
    hostName: 'Diyorbek Sattorov',
    hostPhone: '+998901110122',
    title: 'Bright apartment near Andijan station',
    city: 'Andijan',
    district: 'Center',
    type: ListingType.apartment,
    maxGuests: 3,
    minDays: 1,
    maxDays: 16,
    nightlyPriceUzs: 350000,
    isActive: true,
    amenities: <ListingAmenity>[
      ListingAmenity.wifi,
      ListingAmenity.airConditioner,
      ListingAmenity.kitchen,
      ListingAmenity.privateBathroom,
    ],
    imageUrls: <String>['assets/images/home2.png', 'assets/images/home4.png'],
    description:
        'A comfortable and bright apartment for short city stays and weekend trips.',
    landmark: '40.785811, 72.350483',
    metro: null,
  ),
];

Listing? findExampleListingById(String listingId) {
  for (final listing in kExampleListings) {
    if (listing.id == listingId) {
      return listing;
    }
  }
  return null;
}
